import { FormEvent, useState, useSyncExternalStore } from 'react';
import type { AdminWebCapability } from './contracts';
import './styles.css';

export function App({ administration }: { readonly administration: AdminWebCapability }) {
  const state = useSyncExternalStore((listener) => administration.subscribe(listener), () => administration.getState(), () => administration.getState());
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [customerName, setCustomerName] = useState('');
  if (state.status === 'signed_out' || state.status === 'signing_in') return <main className="login"><section className="login-card"><p className="eyebrow">TAPTIM.E ADMIN</p><h1>Einfach sauber eingerichtet.</h1><p>Melde dich mit deinem Administrator-Konto an.</p><form onSubmit={(event: FormEvent) => { event.preventDefault(); void administration.signIn(email, password); }}><label>E-Mail<input type="email" autoComplete="username" required value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Passwort<input type="password" autoComplete="current-password" required value={password} onChange={(e) => setPassword(e.target.value)} /></label><button disabled={state.status === 'signing_in'}>{state.status === 'signing_in' ? 'Wird geprüft …' : 'Sicher anmelden'}</button></form></section></main>;
  if (state.status === 'loading') return <main className="center"><h1>Einrichtung wird geladen …</h1></main>;
  if (state.status === 'forbidden' || state.status === 'unavailable') return <main className="center"><h1>Nicht verfügbar</h1><p>{state.message}</p><button onClick={() => administration.signOut()}>Zur Anmeldung</button></main>;
  const customerNameById = new Map(state.projection.customers.map((customer) => [customer.id, customer.displayName]));
  return <main><header><div><p className="eyebrow">TAPTIM.E ADMIN</p><h1>{state.projection.organization.name}</h1></div><div className="header-actions"><button className="secondary" onClick={() => administration.refresh()}>Aktualisieren</button><button className="secondary" onClick={() => administration.signOut()}>Abmelden</button></div></header><section className="metrics"><article><strong>{state.projection.customers.length}</strong><span>Kunden</span></article><article><strong>{state.projection.nfcTags.length}</strong><span>NFC-Tags</span></article><article><strong>{state.projection.nfcTags.filter((tag) => tag.assignmentState === 'assigned').length}</strong><span>Zugeordnet</span></article></section><div className="grid"><section className="panel"><h2>Kunden</h2><form className="inline" onSubmit={(event) => { event.preventDefault(); void administration.createCustomer(customerName); setCustomerName(''); }}><label className="sr-only" htmlFor="customer-name">Kundenname</label><input id="customer-name" required maxLength={120} placeholder="Neuer Kundenname" value={customerName} onChange={(e) => setCustomerName(e.target.value)} /><button disabled={state.creating}>{state.creating ? 'Wird angelegt …' : 'Kunde anlegen'}</button></form>{state.notice ? <p role="status" className="notice">{state.notice}</p> : null}<ul>{state.projection.customers.map((customer) => <li key={customer.id}><span>{customer.displayName}</span><small>{customer.active ? 'Aktiv' : 'Inaktiv'}</small></li>)}</ul>{state.projection.customers.length === 0 ? <p className="empty">Noch keine Kunden vorhanden.</p> : null}</section><section className="panel"><h2>NFC-Tags</h2><p className="muted">Neue Tags werden geschützt in der Android-App erfasst.</p><ul>{state.projection.nfcTags.map((tag) => <li key={tag.id}><div><span>{tag.displayName}</span><small>Prüf-Fingerprint {tag.validationFingerprint}</small></div><small>{tag.targetCustomerId === null ? 'Nicht zugeordnet' : customerNameById.get(tag.targetCustomerId) ?? 'Zugeordnet'}</small></li>)}</ul>{state.projection.nfcTags.length === 0 ? <p className="empty">Noch keine Tags registriert.</p> : null}</section></div>{state.projection.nextCursor === null ? null : <div className="more"><button className="secondary" onClick={() => administration.loadMore()}>Weitere Einträge laden</button></div>}</main>;
}
