export const OFFLINE_CAPTURE_LEASE_LIFETIME_MILLISECONDS = 12 * 60 * 60 * 1_000;
export const OFFLINE_CAPTURE_LEASE_REFRESH_WINDOW_MILLISECONDS = 30 * 60 * 1_000;
export const OFFLINE_CLOCK_TOLERANCE_MILLISECONDS = 5 * 60 * 1_000;
export const OFFLINE_AUTOMATIC_EVALUATION_AFTER_EXPIRY_MILLISECONDS = 72 * 60 * 60 * 1_000;

export const OFFLINE_LEASE_PAGE_MAXIMUM_ITEMS = 100;
export const OFFLINE_LEASE_ACTIVATION_MAXIMUM_ITEMS = 4_096;
export const OFFLINE_LEASE_ACTIVATION_MAXIMUM_BYTES = 4 * 1_024 * 1_024;
export const OFFLINE_LEASE_CURSOR_MAXIMUM_BYTES = 256;

export const OFFLINE_QUEUE_MAXIMUM_EVENTS = 256;
export const OFFLINE_QUEUE_MAXIMUM_EVENT_BYTES = 4 * 1_024;
export const OFFLINE_QUEUE_MAXIMUM_TOTAL_BYTES = 1 * 1_024 * 1_024;

export const OFFLINE_REQUEST_MAXIMUM_BYTES = 16 * 1_024;
export const OFFLINE_RESPONSE_MAXIMUM_BYTES = 16 * 1_024;
export const OFFLINE_LEASE_PAGE_RESPONSE_MAXIMUM_BYTES = 64 * 1_024;
export const OFFLINE_REQUEST_TIMEOUT_MILLISECONDS = 10 * 1_000;
export const OFFLINE_RECONCILIATION_MAXIMUM_EVENT_IDS = 25;

export const OFFLINE_RETRY_BASE_MILLISECONDS = 2 * 1_000;
export const OFFLINE_RETRY_CAP_MILLISECONDS = 5 * 60 * 1_000;
export const OFFLINE_RETRY_AFTER_MINIMUM_SECONDS = 1;
export const OFFLINE_RETRY_AFTER_MAXIMUM_SECONDS = 900;
export const OFFLINE_BACKGROUND_MINIMUM_INTERVAL_MINUTES = 15;

export const OFFLINE_INSTALLATION_BINDING_BYTES = 32;
export const OFFLINE_LOOKUP_KEY_BYTES = 32;
export const OFFLINE_BASE64URL_32_BYTE_LENGTH = 43;
export const OFFLINE_SHA256_HEX_LENGTH = 64;

export const OFFLINE_CLOCK_PROOF_VERSION = 1;
export const OFFLINE_PROVENANCE_VERSION = 1;
export const OFFLINE_LOCAL_SCHEMA_VERSION = 2;
