export const TIME_REVIEW_SCHEMA_VERSION = 1 as const;
export const TIME_REVIEW_MAXIMUM_RANGE_MILLISECONDS = 2_678_400_000;
export const TIME_REVIEW_MAXIMUM_QUERY_ROWS = 100;
export const TIME_REVIEW_MAXIMUM_ADJUDICATION_ITEMS = 25;
export const TIME_REVIEW_MAXIMUM_REASON_CHARACTERS = 500;
export const TIME_REVIEW_MAXIMUM_CURSOR_CHARACTERS = 512;
