import { LONGEST_BERLIN_CALENDAR_MONTH_MILLISECONDS } from '@taptime/core';

export const TIME_REVIEW_SCHEMA_VERSION = 1 as const;
export const TIME_REVIEW_MAXIMUM_RANGE_MILLISECONDS = LONGEST_BERLIN_CALENDAR_MONTH_MILLISECONDS;
export const TIME_REVIEW_MAXIMUM_QUERY_ROWS = 100;
export const TIME_REVIEW_MAXIMUM_ADJUDICATION_ITEMS = 25;
export const TIME_REVIEW_MAXIMUM_REASON_CHARACTERS = 500;
export const TIME_REVIEW_MAXIMUM_CURSOR_CHARACTERS = 512;
